### ISSUE TITLE
request documentation on how to use with docker

### ISSUE THREAD

**Issue by isaacimholt** [zytedata/zyte-smartproxy-playwright#9]
we're using the official playwright docker image (https://playwright.dev/docs/docker) how can we integrate zyte-smartproxy-playwright with the dockerfile?

**Comment by geronsv** [comment]
Hi @isaacimholt 
Thanks for the question!
Example of running zyte-smartproxy-playwright from within the playwright docker container:
1. Create a `sample.js` file on your local host (note the `headless: true` launch argument and replace the `<SPM_APIKEY>` with your [API key](https://app.zyte.com/o/smart-proxy-manager/setup)):
```
const { chromium } = require('zyte-smartproxy-playwright'); // Or 'firefox' or 'webkit'

(async () => {
    const browser = await chromium.launch({
        spm_apikey: '<SPM_APIKEY>',
        headless: true,
    });
    console.log('Before new page');
    const page = await browser.newPage({ignoreHTTPSErrors: true});

    console.log('Opening page ...');
    try {
        await page.goto('https://toscrape.com/', {timeout: 180000});
    } catch(err) {
        console.log(err);
    }

    console.log('Taking a screenshot ...');
    await page.screenshot({path: 'screenshot.png'});
    await browser.close();
})();
```
2. [Pull the image](https://playwright.dev/docs/docker#pull-the-image)
```$ docker pull mcr.microsoft.com/playwright:v1.24.2-focal```
3. [Run the image and enter into the docker container](https://playwright.dev/docs/docker#run-the-image)
```$ docker run -it --rm --ipc=host mcr.microsoft.com/playwright:v1.24.2-focal /bin/bash```
4. Once inside the docker container, create a directory for your project, enter into it and install `zyte-smartproxy-playwright`:
```
# mkdir /usr/myapp
# cd /usr/myapp
# npm install zyte-smartproxy-playwright
```
5. On your local host open a new terminal and find the docker CONTAINER ID with the `docker ps` command. After that copy the `sample.js` file from your local host into the docker container:
```
$ docker ps
CONTAINER ID   IMAGE                                        COMMAND       CREATED          STATUS          PORTS     NAMES
2bf97d239d1b   mcr.microsoft.com/playwright:v1.24.2-focal   "/bin/bash"   14 minutes ago   Up 14 minutes             nifty_curran
$ docker cp ~/myapp/sample.js 2bf97d239d1b:/usr/myapp
```
6. Switch back to the terminal inside the docker container and run the `sample.js` file:
```
# node sample.js
```
7. Once it finishes, switch back to the local host terminal and copy the `screenshot.png` from the docker container into the local host:
```
$ docker cp 2bf97d239d1b:/usr/myapp/screenshot.png ~/myapp/screenshot.png
```

P.S.
Some [notes](https://github.com/zytedata/zyte-smartproxy-playwright#notes) to consider.
